version: "3.9"

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moresvet-nextjs
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3005
      - NEXT_PUBLIC_API_URL=https://more-svet-backend.vercel.app/api
      - HOST=0.0.0.0
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: moresvet-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf:/etc/letsencrypt:rw
    depends_on:
      - nextjs
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: moresvet-certbot
    restart: unless-stopped
    volumes:
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf:/etc/letsencrypt:rw
    depends_on:
      - nginx
    command: >
      sh -c "
      certbot certonly --webroot --webroot-path=/var/www/certbot
      --email admin@moresvet.ru
      -d moresvet.ru
      -d www.moresvet.ru
      --agree-tos --no-eff-email --force-renewal &&
      trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done
      "
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
